### Sign Up
GET http://localhost:5000/api/auth/signup

### Login
GET http://localhost:5000/api/auth/login

### Logout
GET http://localhost:5000/api/auth/logout


### Send Message
GET http://localhost:5000/api/messages/send